name: Testar e Gerar Artefato

on: [push]

jobs:
  construir-e-testar:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout do código
      uses: actions/checkout@v4

    - name: 2. Executar e testar (Validação do arquivo)
      run: |
        echo "Iniciando testes..."
        if [ -f dados.txt ]; then
            echo "Sucesso: dados.txt encontrado na raiz!"
        else
            echo "Erro: dados.txt não encontrado."
            exit 1
        fi

    - name: 3. Disponibilizar artefato
      uses: actions/upload-artifact@v4
      with:
        name: artefato-texto
        path: dados.txt

